# Variáveis
@host = http://localhost:3000

### GET Root - Health
GET {{host}}/
Accept: application/json

### Teste - listar todos
GET {{host}}/teste
Accept: application/json

### Teste - buscar por id
GET {{host}}/teste/{{id}}
Accept: application/json

### Teste - criar
POST {{host}}/teste
Content-Type: application/json

{
  "name": "Exemplo"
}

### Teste - atualizar
PUT {{host}}/teste/{{id}}
Content-Type: application/json

{
  "name": "Exemplo Atualizado"
}

### Teste - deletar
DELETE {{host}}/teste/{{id}}


