# Variáveis
@host = http://localhost:3000

### GET Root - Health
GET {{host}}/
Accept: application/json

### Teste - listar todos
GET {{host}}/teste
Accept: application/json

### Teste - buscar por id
# Substitua {{id}} pelo id retornado em CREATE
GET {{host}}/teste/{{id}}
Accept: application/json

### Teste - criar
POST {{host}}/teste
Content-Type: application/json

{
  "name": "Exemplo"
}

### Teste - atualizar
# Substitua {{id}} pelo id do recurso
PUT {{host}}/teste/{{id}}
Content-Type: application/json

{
  "name": "Exemplo Atualizado"
}

### Teste - deletar
# Substitua {{id}} pelo id do recurso
DELETE {{host}}/teste/{{id}}


# Uso rápido (VS Code REST Client):
# - Instale a extensão "REST Client"
# - Abra este arquivo e clique em "Send Request" acima de cada bloco.
# Dica: primeiro rode POST para obter um id, depois use-o nos requests que precisam de {{id}}.
